name: Deploy Pomodoro Timer

on:
  push:
    branches:
      - master # Trigger workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/pomodoro-timer:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/pomodoro-timer:latest

    # Step 5: Deploy to Ubuntu VPS
    - name: Deploy to Ubuntu VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/pomodoro-timer:latest
          docker stop pomodoro-container || true
          docker rm pomodoro-container || true
          docker run -d -p 3000:3000 --name pomodoro-container ${{ secrets.DOCKER_USERNAME }}/pomodoro-timer:latest
