name: Deploy Pomodoro Timer

on:
  push:
    branches:
      - master # Trigger workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t pomodoro-timer ./frontend

    # Step 4: Deploy to Ubuntu VPS
    - name: Deploy to Ubuntu VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          docker save pomodoro-timer | ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'docker load'
          docker stop pomodoro-container || true
          docker rm pomodoro-container || true
          docker run -d -p 3000:3000 --name pomodoro-container pomodoro-timer
